# Generated by Django 3.2.3 on 2021-09-20 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='diaHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado')], max_length=9)),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inscAbierta', models.BooleanField(default=False)),
                ('habilitado', models.BooleanField(default=False)),
                ('practico', models.BooleanField(default=True)),
                ('cantHoras', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(4)])),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('cenForm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CFP.centrodeformacion')),
                ('diasHorarios', models.ManyToManyField(to='CFP.diaHora')),
            ],
        ),
        migrations.AddField(
            model_name='centrodeformacion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CFP.localidad'),
        ),
    ]
