# Generated by Django 3.2.3 on 2021-09-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diahora',
            name='horaInicio',
            field=models.TimeField(default="05:00"),
            preserve_default=False,
        ),
    ]
