# Generated by Django 3.2.3 on 2021-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0003_auto_20210922_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='diahora',
            name='horaFin',
            field=models.CharField(default='nada', max_length=5),
            preserve_default=False,
        ),
    ]
