# Generated by Django 3.2.3 on 2021-09-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0004_auto_20210922_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diahora',
            name='horaFin',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='diahora',
            name='horaInicio',
            field=models.CharField(max_length=6),
        ),
    ]
