# Generated by Django 3.2.3 on 2021-10-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0005_auto_20210922_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diahora',
            name='hora',
        ),
    ]
