# Generated by Django 3.2.3 on 2021-11-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_alter_alumno_dniimg'),
        ('CFP', '0007_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='practico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.profesor'),
        ),
    ]
