# Generated by Django 3.2.3 on 2021-11-13 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0008_auto_20211106_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupoMax',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='cupoMin',
            field=models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
