# Generated by Django 3.2.3 on 2021-11-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0009_auto_20211113_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantAl',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
