# Generated by Django 3.2.3 on 2021-11-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0010_curso_cantal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='cantAl',
        ),
    ]
