# Generated by Django 3.2.3 on 2021-09-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Autorizacion',
            field=models.ImageField(upload_to='alumnos'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='DniImg',
            field=models.ImageField(upload_to='alumnos'),
        ),
    ]
