# Generated by Django 3.2.3 on 2021-10-13 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20210921_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcAsist', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('notaCurso', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Usuarios.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CFP.curso')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(through='Usuarios.CursoAlumno', to='CFP.Curso'),
        ),
    ]
