# Generated by Django 3.2.3 on 2021-10-13 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_auto_20211013_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoalumno',
            name='porcAsist',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
