# Generated by Django 3.2.3 on 2021-10-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_cursoalumno_porcasist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Autorizacion',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='DniImg',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos'),
        ),
    ]
