# Generated by Django 3.2.3 on 2021-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20211020_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='DniImg',
            field=models.ImageField(default='null', upload_to='alumnos'),
            preserve_default=False,
        ),
    ]
