# Generated by Django 3.2.3 on 2021-11-07 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_alter_alumno_dniimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoalumno',
            name='notaCurso',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='cursoalumno',
            name='porcAsist',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
