# Generated by Django 3.2.3 on 2021-11-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFP', '0009_auto_20211113_2230'),
        ('Usuarios', '0007_auto_20211107_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Usuarios.appuser')),
                ('telefono', models.CharField(max_length=20)),
                ('cfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CFP.centrodeformacion')),
            ],
        ),
    ]
