# Generated by Django 3.2.3 on 2021-11-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_preceptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='es_preceptor',
            field=models.BooleanField(default=False),
        ),
    ]
