# Generated by Django 3.2.3 on 2021-12-04 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_profesor_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(20000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
