# Generated by Django 3.2.3 on 2021-12-05 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_auto_20211205_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='altura',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
